# Generated by Django 5.0.1 on 2024-02-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Good'), ('C', 'C - Satisfactory'), ('D', 'D - Limited'), ('E', 'E - Very Low'), ('F', 'F - Failed/Incomplete')], default='C', max_length=1),
        ),
    ]
