# Generated by Django 5.0.1 on 2024-02-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_subject_end_date_subject_exam_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='badge_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
