# Generated by Django 5.0.1 on 2024-02-05 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_quest_badge_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='progress',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
