# Generated by Django 5.0.1 on 2024-02-07 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_profile_avatar_url_delete_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam_date',
            field=models.DateField(default=datetime.date(2024, 2, 8), verbose_name='Date'),
        ),
    ]
