# Generated by Django 5.0.1 on 2024-02-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_subject_exam_date'),
        ('main_app', '0014_remove_profile_avatar_style_profile_avatar_url'),
    ]

    operations = [
    ]
