# Generated by Django 5.0.1 on 2024-02-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_assignment_complete_date_assignment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='complete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
